"""cascade delete

Revision ID: 28e1e033a04d
Revises: 8456e7343082
Create Date: 2025-06-24 03:19:31.172543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e1e033a04d'
down_revision = '8456e7343082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feedbacks_recipe_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_feedbacks_recipe_id_recipes'), 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_files_recipe_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_files_recipe_id_recipes'), 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_files_recipe_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_files_recipe_id_recipes'), 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feedbacks_recipe_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_feedbacks_recipe_id_recipes'), 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
