"""recipe steps text

Revision ID: c278c4c75491
Revises: 65f6f13721ff
Create Date: 2025-06-25 16:43:40.761114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c278c4c75491'
down_revision = '65f6f13721ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('steps',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('steps',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
